name: Publish Docker image

on:
  push:
    # Pattern matched against refs/tags
    tags:
      - '*'

jobs:
  publish_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: leventehunyadi/md2conf
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile
          tags: "latest,${{ github.ref_name }}"
